name: base
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - flake8
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - transformers
    - datasets
    - pytest
    
